### ISSUE TITLE
Issue with screen tearing

### ISSUE THREAD

**Issue by ACrazyTown** [polybiusproxy/hxCodec#162]
I'm having an issue with screen tearing on the (almost) latest version of hxCodec (commit 3a784d0), iirc this didn't happen before when I was using an old version of hxCodec (before it was even called hxCodec)

I'm on Windows 10 with a pretty good PC, it can surely handle a simple video.

![image](https://user-images.githubusercontent.com/47027981/178601741-8307e638-9b88-4922-96f4-e4312079946f.png)

**Comment by MAJigsaw77** [comment]
Was the game in full screen?

**Comment by MAJigsaw77** [comment]
I think is because of the buffer that display the video

**Comment by MAJigsaw77** [comment]
@ACrazyTown test now, it should be fixed

**Comment by ActualMandM** [comment]
Issue still seems to persist for me with the latest commit.
![vlcsnap-2022-07-21-21h33m23s001](https://user-images.githubusercontent.com/15317421/180364186-d71ea070-98ff-4409-9b49-77630e7a77ce.png)

https://user-images.githubusercontent.com/15317421/180364160-4afedea2-58d6-4029-b32e-ca43b1bcd59d.mp4

**Comment by polybiusproxy** [comment]
> Issue still seems to persist for me with the latest commit. ![vlcsnap-2022-07-21-21h33m23s001](https://user-images.githubusercontent.com/15317421/180364186-d71ea070-98ff-4409-9b49-77630e7a77ce.png)
> 
>  tear.mp4

Results seem better though!

**Comment by MAJigsaw77** [comment]
> Issue still seems to persist for me with the latest commit. ![vlcsnap-2022-07-21-21h33m23s001](https://user-images.githubusercontent.com/15317421/180364186-d71ea070-98ff-4409-9b49-77630e7a77ce.png)
> 
>  tear.mp4

I think we will need to rewrite the buffer code

**Comment by MAJigsaw77** [comment]
I don't see another way to fix it

**Comment by polybiusproxy** [comment]
@ACrazyTown @ActualMandM Please test the new commit!

**Comment by MAJigsaw77** [comment]
@ACrazyTown @ActualMandM if the screen tearing continues try to run the video in window mode not full screen

**Comment by ACrazyTown** [comment]
From what I've noticed, it still happens (although now quite subtle) but mostly in fullscreen mode. Windowed seems fine from what I can tell?

**Comment by MAJigsaw77** [comment]
But now is different isn't it

**Comment by MAJigsaw77** [comment]
Also in full screen, that is normal to happen

**Comment by polybiusproxy** [comment]
Closing this issue due to inactivity. If it keeps happening, feel free to re-open it.
